// 获取 book category
export const GET_BOOK_CATEGORY_PENDING = 'GET_BOOK_CATEGORY_PENDING';
export const GET_BOOK_CATEGORY_SUCCESS = 'GET_BOOK_CATEGORY_SUCCESS';
export const GET_BOOK_CATEGORY_FAILURE = 'GET_BOOK_CATEGORY_FAILURE';

// search book by tag
export const SEARCH_BOOK_BY_TAGS_PENDING = 'SEARCH_BOOK_BY_TAGS_PENDING';
export const SEARCH_BOOK_BY_TAGS_SUCCESS = 'SEARCH_BOOK_BY_TAGS_SUCCESS';
export const SEARCH_BOOK_BY_TAGS_FAILURE = 'SEARCH_BOOK_BY_TAGS_FAILURE';
