// 点击 table row，显示出弹窗
export const SAVE_CURRENT_CUSTOMER_INFO = 'SAVE_CURRENT_CUSTOMER_INFO';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const FILL_CUSTOMER_INFO = 'FILL_CUSTOMER_INFO';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CUSTOMER_INFO_BE_EDITED = 'CUSTOMER_INFO_BE_EDITED';
export const CANCLE_BE_EDITED_CUSTOMER_INFO = 'CANCLE_BE_EDITED_CUSTOMER_INFO';
