// 点击 table row，显示出弹窗
export const SAVE_CURRENT_CUSTOMER_INFO = 'SAVE_CURRENT_CUSTOMER_INFO';
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const FILL_CUSTOMER_INFO = 'FILL_CUSTOMER_INFO';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';
export const INCREASE_BE_EDITED_NUMBER = 'INCREASE_BE_EDITED_NUMBER';
export const DECREASE_BE_EDITED_NUMBER = 'DECREASE_BE_EDITED_NUMBER';
export const RESET_CUSTOMER_INFO = 'RESET_CUSTOMER_INFO';
